/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransmissaoRouteImport } from './routes/transmissao'
import { Route as SalaDeChamadaRouteImport } from './routes/sala-de-chamada'
import { Route as ResultadosRouteImport } from './routes/resultados'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as RecordesRouteImport } from './routes/recordes'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as ProvasRouteImport } from './routes/provas'
import { Route as ProtestosRouteImport } from './routes/protestos'
import { Route as InscricoesRouteImport } from './routes/inscricoes'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as EstatisticasRouteImport } from './routes/estatisticas'
import { Route as CronometragemRouteImport } from './routes/cronometragem'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CompeticoesRouteImport } from './routes/competicoes'
import { Route as ClubesRouteImport } from './routes/clubes'
import { Route as BalizamentoRouteImport } from './routes/balizamento'
import { Route as AtletasRouteImport } from './routes/atletas'
import { Route as ArbitragemRouteImport } from './routes/arbitragem'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProvasNovaRouteImport } from './routes/provas.nova'
import { Route as CompeticoesNovaRouteImport } from './routes/competicoes.nova'
import { Route as CompeticoesIdProvasRouteImport } from './routes/competicoes.$id.provas'
import { Route as CompeticoesIdGerenciarRouteImport } from './routes/competicoes.$id.gerenciar'

const TransmissaoRoute = TransmissaoRouteImport.update({
  id: '/transmissao',
  path: '/transmissao',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaDeChamadaRoute = SalaDeChamadaRouteImport.update({
  id: '/sala-de-chamada',
  path: '/sala-de-chamada',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadosRoute = ResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordesRoute = RecordesRouteImport.update({
  id: '/recordes',
  path: '/recordes',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvasRoute = ProvasRouteImport.update({
  id: '/provas',
  path: '/provas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtestosRoute = ProtestosRouteImport.update({
  id: '/protestos',
  path: '/protestos',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricoesRoute = InscricoesRouteImport.update({
  id: '/inscricoes',
  path: '/inscricoes',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EstatisticasRoute = EstatisticasRouteImport.update({
  id: '/estatisticas',
  path: '/estatisticas',
  getParentRoute: () => rootRouteImport,
} as any)
const CronometragemRoute = CronometragemRouteImport.update({
  id: '/cronometragem',
  path: '/cronometragem',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CompeticoesRoute = CompeticoesRouteImport.update({
  id: '/competicoes',
  path: '/competicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubesRoute = ClubesRouteImport.update({
  id: '/clubes',
  path: '/clubes',
  getParentRoute: () => rootRouteImport,
} as any)
const BalizamentoRoute = BalizamentoRouteImport.update({
  id: '/balizamento',
  path: '/balizamento',
  getParentRoute: () => rootRouteImport,
} as any)
const AtletasRoute = AtletasRouteImport.update({
  id: '/atletas',
  path: '/atletas',
  getParentRoute: () => rootRouteImport,
} as any)
const ArbitragemRoute = ArbitragemRouteImport.update({
  id: '/arbitragem',
  path: '/arbitragem',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvasNovaRoute = ProvasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => ProvasRoute,
} as any)
const CompeticoesNovaRoute = CompeticoesNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => CompeticoesRoute,
} as any)
const CompeticoesIdProvasRoute = CompeticoesIdProvasRouteImport.update({
  id: '/$id/provas',
  path: '/$id/provas',
  getParentRoute: () => CompeticoesRoute,
} as any)
const CompeticoesIdGerenciarRoute = CompeticoesIdGerenciarRouteImport.update({
  id: '/$id/gerenciar',
  path: '/$id/gerenciar',
  getParentRoute: () => CompeticoesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arbitragem': typeof ArbitragemRoute
  '/atletas': typeof AtletasRoute
  '/balizamento': typeof BalizamentoRoute
  '/clubes': typeof ClubesRoute
  '/competicoes': typeof CompeticoesRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/cronometragem': typeof CronometragemRoute
  '/estatisticas': typeof EstatisticasRoute
  '/financeiro': typeof FinanceiroRoute
  '/inscricoes': typeof InscricoesRoute
  '/protestos': typeof ProtestosRoute
  '/provas': typeof ProvasRouteWithChildren
  '/rankings': typeof RankingsRoute
  '/recordes': typeof RecordesRoute
  '/relatorios': typeof RelatoriosRoute
  '/resultados': typeof ResultadosRoute
  '/sala-de-chamada': typeof SalaDeChamadaRoute
  '/transmissao': typeof TransmissaoRoute
  '/competicoes/nova': typeof CompeticoesNovaRoute
  '/provas/nova': typeof ProvasNovaRoute
  '/competicoes/$id/gerenciar': typeof CompeticoesIdGerenciarRoute
  '/competicoes/$id/provas': typeof CompeticoesIdProvasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arbitragem': typeof ArbitragemRoute
  '/atletas': typeof AtletasRoute
  '/balizamento': typeof BalizamentoRoute
  '/clubes': typeof ClubesRoute
  '/competicoes': typeof CompeticoesRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/cronometragem': typeof CronometragemRoute
  '/estatisticas': typeof EstatisticasRoute
  '/financeiro': typeof FinanceiroRoute
  '/inscricoes': typeof InscricoesRoute
  '/protestos': typeof ProtestosRoute
  '/provas': typeof ProvasRouteWithChildren
  '/rankings': typeof RankingsRoute
  '/recordes': typeof RecordesRoute
  '/relatorios': typeof RelatoriosRoute
  '/resultados': typeof ResultadosRoute
  '/sala-de-chamada': typeof SalaDeChamadaRoute
  '/transmissao': typeof TransmissaoRoute
  '/competicoes/nova': typeof CompeticoesNovaRoute
  '/provas/nova': typeof ProvasNovaRoute
  '/competicoes/$id/gerenciar': typeof CompeticoesIdGerenciarRoute
  '/competicoes/$id/provas': typeof CompeticoesIdProvasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arbitragem': typeof ArbitragemRoute
  '/atletas': typeof AtletasRoute
  '/balizamento': typeof BalizamentoRoute
  '/clubes': typeof ClubesRoute
  '/competicoes': typeof CompeticoesRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/cronometragem': typeof CronometragemRoute
  '/estatisticas': typeof EstatisticasRoute
  '/financeiro': typeof FinanceiroRoute
  '/inscricoes': typeof InscricoesRoute
  '/protestos': typeof ProtestosRoute
  '/provas': typeof ProvasRouteWithChildren
  '/rankings': typeof RankingsRoute
  '/recordes': typeof RecordesRoute
  '/relatorios': typeof RelatoriosRoute
  '/resultados': typeof ResultadosRoute
  '/sala-de-chamada': typeof SalaDeChamadaRoute
  '/transmissao': typeof TransmissaoRoute
  '/competicoes/nova': typeof CompeticoesNovaRoute
  '/provas/nova': typeof ProvasNovaRoute
  '/competicoes/$id/gerenciar': typeof CompeticoesIdGerenciarRoute
  '/competicoes/$id/provas': typeof CompeticoesIdProvasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arbitragem'
    | '/atletas'
    | '/balizamento'
    | '/clubes'
    | '/competicoes'
    | '/configuracoes'
    | '/cronometragem'
    | '/estatisticas'
    | '/financeiro'
    | '/inscricoes'
    | '/protestos'
    | '/provas'
    | '/rankings'
    | '/recordes'
    | '/relatorios'
    | '/resultados'
    | '/sala-de-chamada'
    | '/transmissao'
    | '/competicoes/nova'
    | '/provas/nova'
    | '/competicoes/$id/gerenciar'
    | '/competicoes/$id/provas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arbitragem'
    | '/atletas'
    | '/balizamento'
    | '/clubes'
    | '/competicoes'
    | '/configuracoes'
    | '/cronometragem'
    | '/estatisticas'
    | '/financeiro'
    | '/inscricoes'
    | '/protestos'
    | '/provas'
    | '/rankings'
    | '/recordes'
    | '/relatorios'
    | '/resultados'
    | '/sala-de-chamada'
    | '/transmissao'
    | '/competicoes/nova'
    | '/provas/nova'
    | '/competicoes/$id/gerenciar'
    | '/competicoes/$id/provas'
  id:
    | '__root__'
    | '/'
    | '/arbitragem'
    | '/atletas'
    | '/balizamento'
    | '/clubes'
    | '/competicoes'
    | '/configuracoes'
    | '/cronometragem'
    | '/estatisticas'
    | '/financeiro'
    | '/inscricoes'
    | '/protestos'
    | '/provas'
    | '/rankings'
    | '/recordes'
    | '/relatorios'
    | '/resultados'
    | '/sala-de-chamada'
    | '/transmissao'
    | '/competicoes/nova'
    | '/provas/nova'
    | '/competicoes/$id/gerenciar'
    | '/competicoes/$id/provas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArbitragemRoute: typeof ArbitragemRoute
  AtletasRoute: typeof AtletasRoute
  BalizamentoRoute: typeof BalizamentoRoute
  ClubesRoute: typeof ClubesRoute
  CompeticoesRoute: typeof CompeticoesRouteWithChildren
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  CronometragemRoute: typeof CronometragemRoute
  EstatisticasRoute: typeof EstatisticasRoute
  FinanceiroRoute: typeof FinanceiroRoute
  InscricoesRoute: typeof InscricoesRoute
  ProtestosRoute: typeof ProtestosRoute
  ProvasRoute: typeof ProvasRouteWithChildren
  RankingsRoute: typeof RankingsRoute
  RecordesRoute: typeof RecordesRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ResultadosRoute: typeof ResultadosRoute
  SalaDeChamadaRoute: typeof SalaDeChamadaRoute
  TransmissaoRoute: typeof TransmissaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transmissao': {
      id: '/transmissao'
      path: '/transmissao'
      fullPath: '/transmissao'
      preLoaderRoute: typeof TransmissaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sala-de-chamada': {
      id: '/sala-de-chamada'
      path: '/sala-de-chamada'
      fullPath: '/sala-de-chamada'
      preLoaderRoute: typeof SalaDeChamadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultados': {
      id: '/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof ResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordes': {
      id: '/recordes'
      path: '/recordes'
      fullPath: '/recordes'
      preLoaderRoute: typeof RecordesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provas': {
      id: '/provas'
      path: '/provas'
      fullPath: '/provas'
      preLoaderRoute: typeof ProvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protestos': {
      id: '/protestos'
      path: '/protestos'
      fullPath: '/protestos'
      preLoaderRoute: typeof ProtestosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricoes': {
      id: '/inscricoes'
      path: '/inscricoes'
      fullPath: '/inscricoes'
      preLoaderRoute: typeof InscricoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estatisticas': {
      id: '/estatisticas'
      path: '/estatisticas'
      fullPath: '/estatisticas'
      preLoaderRoute: typeof EstatisticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cronometragem': {
      id: '/cronometragem'
      path: '/cronometragem'
      fullPath: '/cronometragem'
      preLoaderRoute: typeof CronometragemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competicoes': {
      id: '/competicoes'
      path: '/competicoes'
      fullPath: '/competicoes'
      preLoaderRoute: typeof CompeticoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubes': {
      id: '/clubes'
      path: '/clubes'
      fullPath: '/clubes'
      preLoaderRoute: typeof ClubesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/balizamento': {
      id: '/balizamento'
      path: '/balizamento'
      fullPath: '/balizamento'
      preLoaderRoute: typeof BalizamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atletas': {
      id: '/atletas'
      path: '/atletas'
      fullPath: '/atletas'
      preLoaderRoute: typeof AtletasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arbitragem': {
      id: '/arbitragem'
      path: '/arbitragem'
      fullPath: '/arbitragem'
      preLoaderRoute: typeof ArbitragemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provas/nova': {
      id: '/provas/nova'
      path: '/nova'
      fullPath: '/provas/nova'
      preLoaderRoute: typeof ProvasNovaRouteImport
      parentRoute: typeof ProvasRoute
    }
    '/competicoes/nova': {
      id: '/competicoes/nova'
      path: '/nova'
      fullPath: '/competicoes/nova'
      preLoaderRoute: typeof CompeticoesNovaRouteImport
      parentRoute: typeof CompeticoesRoute
    }
    '/competicoes/$id/provas': {
      id: '/competicoes/$id/provas'
      path: '/$id/provas'
      fullPath: '/competicoes/$id/provas'
      preLoaderRoute: typeof CompeticoesIdProvasRouteImport
      parentRoute: typeof CompeticoesRoute
    }
    '/competicoes/$id/gerenciar': {
      id: '/competicoes/$id/gerenciar'
      path: '/$id/gerenciar'
      fullPath: '/competicoes/$id/gerenciar'
      preLoaderRoute: typeof CompeticoesIdGerenciarRouteImport
      parentRoute: typeof CompeticoesRoute
    }
  }
}

interface CompeticoesRouteChildren {
  CompeticoesNovaRoute: typeof CompeticoesNovaRoute
  CompeticoesIdGerenciarRoute: typeof CompeticoesIdGerenciarRoute
  CompeticoesIdProvasRoute: typeof CompeticoesIdProvasRoute
}

const CompeticoesRouteChildren: CompeticoesRouteChildren = {
  CompeticoesNovaRoute: CompeticoesNovaRoute,
  CompeticoesIdGerenciarRoute: CompeticoesIdGerenciarRoute,
  CompeticoesIdProvasRoute: CompeticoesIdProvasRoute,
}

const CompeticoesRouteWithChildren = CompeticoesRoute._addFileChildren(
  CompeticoesRouteChildren,
)

interface ProvasRouteChildren {
  ProvasNovaRoute: typeof ProvasNovaRoute
}

const ProvasRouteChildren: ProvasRouteChildren = {
  ProvasNovaRoute: ProvasNovaRoute,
}

const ProvasRouteWithChildren =
  ProvasRoute._addFileChildren(ProvasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArbitragemRoute: ArbitragemRoute,
  AtletasRoute: AtletasRoute,
  BalizamentoRoute: BalizamentoRoute,
  ClubesRoute: ClubesRoute,
  CompeticoesRoute: CompeticoesRouteWithChildren,
  ConfiguracoesRoute: ConfiguracoesRoute,
  CronometragemRoute: CronometragemRoute,
  EstatisticasRoute: EstatisticasRoute,
  FinanceiroRoute: FinanceiroRoute,
  InscricoesRoute: InscricoesRoute,
  ProtestosRoute: ProtestosRoute,
  ProvasRoute: ProvasRouteWithChildren,
  RankingsRoute: RankingsRoute,
  RecordesRoute: RecordesRoute,
  RelatoriosRoute: RelatoriosRoute,
  ResultadosRoute: ResultadosRoute,
  SalaDeChamadaRoute: SalaDeChamadaRoute,
  TransmissaoRoute: TransmissaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
